### ISSUE TITLE
AttributeError: module 'tpm_futurepcr' has no attribute 'main'

### ISSUE THREAD

**Issue by aospan** [grawity/tpm_futurepcr#17]
Hello Fellow Developers!

Trying to use your amazing project but hit an issue on a freshly prepared Ubuntu 22.04 docker image:

```
root@457c14f410a7:/# tpm_futurepcr -L 0,2,4,7 -o pcrvalues.bin
Traceback (most recent call last):
  File "/usr/local/bin/tpm_futurepcr", line 33, in <module>
    sys.exit(load_entry_point('tpm-futurepcr==1.5', 'console_scripts', 'tpm_futurepcr')())
  File "/usr/local/bin/tpm_futurepcr", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'tpm_futurepcr' has no attribute 'main'
```

Steps to reproduce:
```
git clone -b futurepcr https://github.com/aospan/docker-tpm2-tools.git
cd docker-tpm2-tools/
sudo docker build -t aospan/tpm2-tools-futurepcr .
sudo docker run --privileged -v /sys/kernel/security/:/sys/kernel/security/ -it aospan/tpm2-tools-futurepcr tpm_futurepcr -L 0,2,4,7 -o pcrvalues.bin
```

Thanks!

**Comment by grawity** [comment]
@flixman

**Comment by flixman** [comment]
@grawity My apologies for being offline so much time: I have been caught by work and... I did not receive any notification when you mentioned me :-/. I see that the changes I committed where moved to a felix/unfinished branch. Besides this open issue, what else is missing?

**Comment by flixman** [comment]
@grawity ? Did you see my last comment?
